server:
  port: 8080

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    user-service:
      path: /user/**
      url: http://127.0.0.1:8083/
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:8082/

knightech.security.jwt.secret: otherpeopledontknowit
