spring:
  application:
    name: api-gateway
zuul:
  routes:
    auth-center:
      path: /auth-center/login/**
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    user-service:
      path: /user-service/**
    backend-service:
      path: /backend-service/**
knightech:
  security:
    jwt:
      secret: otherpeopledontknowit