spring:
  application:
    name: auth-center
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}
knightech:
  security:
    jwt:
      secret: otherpeopledontknowit