apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-center
  labels:
    app: auth-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-center
  template:
    metadata:
      labels:
        app: auth-center
    spec:
      containers:
      - name: department
        image: petecknight/auth-center:0.1.1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-center
  labels:
    app: auth-center
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: auth-center